name: This is a test name
description: This is a test description

inputs:
  name:
    description: 'Your name'
    default: 'No name provided'
    required: false
runs:
  using: 'composite'
  steps:
    - run: echo Hello ${{ inputs.name }}.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: pwsh
