name: Call a reusable workflow

on: push

jobs:
  call_workflow_passing_data:
    name: Call workflow passing data
    uses: ./.github/workflows/called-workflow.yml@main
    with:
      username: mona
    secrets:
      token: XXX-XXX-XXX-XXX
