name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  echo_input_and_secret:
    name: Echo input and secret
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username }} ${{ secrets.token }}
