name: Call a reusable workflow

on: push

jobs:
  call_workflow_passing_data:
    name: Call workflow passing data
    uses: mrseanbaines/github-actions-example/.github/workflows/called-workflow.yml@v1
    with:
      username: mona
    secrets:
      token: XXX-XXX-XXX-XXX
