name: Functions

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        if: contains(fromJson('["staging", "feature", "production", "experiment-staging", "experiment-production"]'), "experiment-staging")
        run: echo It works 🎉
