name: Functions

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: echo ${{ contains(fromJson('["hello-world", "banana"]'), 'hello-world') }}

      - name: Bar
        run: echo ${{ contains(fromJson('["hi-world", "banana"]'), 'hello-world') }}

      - name: Baz
        run: echo ${{ contains(fromJson('["hello-world", "banana"]'), 'hello') }}
