on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: Hello
      output2: World

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
