name: Test

on:
  repository_dispatch:
    types: foo_bar_baz
  push:
    branches:
      - master

jobs:
  test:
    env:
      MY_ENV_VAR: ${{ github.event_name == 'push' }}
      FOO: hello world
      BANANA: ${{ secrets.BANANA }}
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p path/to/artifact

      - run: echo Hello, Sean! > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: path/to/artifact

      - name: Set Env Variables
        if: github.event_name == 'push'
        run: |
          echo ::set-env name=BAR::$FOO
          echo ::set-env name=HELLO::$BANANA
      - uses: actions/checkout@v2
      - run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.client_payload.environment: ${{ github.event.client_payload.environment }}
          echo github.ref: ${{ github.ref }}
          echo github.event.action: ${{ github.event.action }}
          echo MY_ENV_VAR: $MY_ENV_VAR
          echo ONE: $FOO
          echo TWO: $BAR
          echo THREE: $HELLO
          echo FOUR: $BANANA

      - uses: actions/download-artifact@v1
        with:
          name: my-artifact

      - run: cat my-artifact
