name: Repository Dispatch

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    # if: github.event_name == 'repository_dispatch' && github.event.action == 'testing_123'
    # if: github.event.client_payload.environment == 'production' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.client_payload.environment: ${{ github.event.client_payload.environment }}
          echo github.ref: ${{ github.ref }}
          echo github.event: ${{ JSON.stringify(github.event) }}
