name: Repository Dispatch

on:
  repository_dispatch:
    types: foo_bar_baz
  push:
    branches:
      - master

jobs:
  build:
    env:
      my_env_var: ${{ 1 + 1 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.client_payload.environment: ${{ github.event.client_payload.environment }}
          echo github.ref: ${{ github.ref }}
          echo github.event.action: ${{ github.event.action }}
          echo my_env_var: ${{ my_env_var }}
