name: Repository Dispatch

on:
  repository_dispatch:
    types: foo_bar_baz
  push:
    branches:
      - master

jobs:
  build:
    env:
      MY_ENV_VAR: ${{ github.event_name == 'push' }}
      FOO: hello world
      BANANA: ${{ secrets.BANANA }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Env Variables
        if: github.event_name == 'push'
        run: |
          echo ::set-env name=BAR::$FOO
          echo ::set-env name=HELLO::$BANANA
      - uses: actions/checkout@v2
      - run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.client_payload.environment: ${{ github.event.client_payload.environment }}
          echo github.ref: ${{ github.ref }}
          echo github.event.action: ${{ github.event.action }}
          echo MY_ENV_VAR: $MY_ENV_VAR
          # echo FOO: $FOO
          echo BAR: $BAR
