name: Repository Dispatch

on:
  repository_dispatch:
    types: foo_bar_baz
  push:
    branches:
      - master

jobs:
  build:
    env:
      MY_ENV_VAR: ${{ 1 == 1 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.client_payload.environment: ${{ github.event.client_payload.environment }}
          echo github.ref: ${{ github.ref }}
          echo github.event.action: ${{ github.event.action }}
          echo MY_ENV_VAR: $MY_ENV_VAR
      - run: echo foo bar baz
        if: $MY_ENV_VAR
